# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8da80edc286a9e1eaf8842e826ed6df64b26c266a1f153dc121a83296b8cc5b648870c3d91a11979b14972f403c5d323993514d4b69f44670e31932a0c9e0ab

test:
  secret_key_base: ccf0b7b19924a3a6d4fb247bcac0f42ddc0cdfd93313d3ab4b5084df948e31897de56d14bf233894c85761851f9732b1d1f1f4d73711f0cbf351b03d6295feee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
